import { useEffect, useState } from 'react';
import { Link, useNavigate, useSearchParams } from 'react-router-dom';
import { ShieldCheck } from 'lucide-react';
import { Button, Input } from '../components/common';
import { UiLanguageToggle } from '../components/i18n/UiLanguageToggle';
import { useAuth } from '../hooks';
import { useUiLanguage } from '../contexts/UiLanguageContext';
import { authApi } from '../api/auth';
import { accountErrorMessage } from '../utils/accountError';

export default function LoginPage() {
  const { accountMode, accountState, passwordSet, refreshStatus, registrationMode, multiUserEnabled } = useAuth();
  const [joining, setJoining] = useState(false);
  const { localize: l } = useUiLanguage();
  const navigate = useNavigate();
  const [params] = useSearchParams();
  const raw = params.get('redirect') || '';
  const redirect = raw.startsWith('/') && !raw.startsWith('//') && !raw.includes('\\') && !raw.startsWith('/login') ? raw : '/';
  const register = joining || (accountMode ? accountState === 'register' : !passwordSet);
  const migrate = accountMode && accountState === 'migrate';
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [confirmation, setConfirmation] = useState('');
  const [token, setToken] = useState('');
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState<unknown>();
  const [mismatch, setMismatch] = useState(false);
  const title = joining ? l('创建你的私有工作区', 'Create your private workspace') : migrate ? l('补全管理员账户', 'Complete your admin account') : register ? l('创建管理员账户', 'Create your admin account') : l('欢迎回来', 'Welcome back');
  useEffect(() => { document.title = title + ' · AI Stock'; }, [title]);

  return <main className="min-h-screen bg-background px-5 py-10 text-foreground sm:py-16">
    <header className="mx-auto flex w-full max-w-5xl items-center justify-between gap-4">
      <div className="min-w-0">
        <span className="text-xl font-semibold tracking-tight">AI Stock</span>
        <p className="mt-2 max-w-lg text-sm leading-6 text-secondary-text">{l('用 AI 赋能每一位股票交易者，成为自己的超级投研个体。', 'Empower every stock trader with AI to become a one-person research powerhouse.')}</p>
      </div><UiLanguageToggle />
    </header>
    <section className="mx-auto mt-14 w-full max-w-md sm:mt-20" aria-labelledby="account-title">
      <ShieldCheck size={28} className="mb-5 text-primary" aria-hidden />
      <h1 id="account-title" className="text-3xl font-semibold tracking-tight">{title}</h1>
      <p className="mt-3 text-sm leading-6 text-secondary-text">{joining
        ? l('使用受邀邮箱与邀请码注册。对话、报告和持仓仅属于你，累计试用额度为 20 万 Token。', 'Register with your invited email and invitation code. Your chats, reports and holdings are private, with a lifetime allowance of 200,000 tokens.')
        : migrate
        ? l('验证原管理员密码并补充邮箱。已有持仓、报告和配置都会保留。', 'Verify your existing admin password and add an email. Your holdings, reports and settings will be preserved.')
        : register
          ? l('为你的投研工作区创建唯一管理员。邮箱仅用作登录账号，不会发送验证邮件。', 'Create the sole administrator for your research workspace. Email is a login identifier; no verification email is sent.')
          : l('登录你的投研工作区，继续研究和跟踪持仓。', 'Sign in to continue your research and portfolio tracking.')}</p>
      <form className="mt-8 space-y-5" onSubmit={async e => {
        e.preventDefault(); setError(undefined); setMismatch(false);
        if (register && password !== confirmation) { setMismatch(true); return; }
        setBusy(true);
        try {
          if (accountMode && (register || migrate)) {
            await authApi.register({ email, password: register ? password : '', passwordConfirm: confirmation, currentPassword: migrate ? password : '', setupToken: joining ? '' : token, ...(joining ? { memberRegistration: true, inviteCode: token } : {}) });
          } else { await authApi.login(password, register ? confirmation : undefined, accountMode ? email : undefined); }
          await refreshStatus();
          if (multiUserEnabled) window.location.assign(redirect);
          else navigate(redirect, { replace: true });
        } catch (err) { setError(err); }
        finally { setBusy(false); }
      }}>
        {accountMode && <Input label={l('邮箱', 'Email')} type="email" required maxLength={254} autoComplete="username" value={email} onChange={e => setEmail(e.target.value)} disabled={busy} />}
        <Input label={migrate ? l('原管理员密码', 'Existing admin password') : l('密码', 'Password')} type="password" required maxLength={register ? 128 : 1024} minLength={register ? accountMode ? 8 : 6 : undefined} allowTogglePassword autoComplete={register ? 'new-password' : 'current-password'} value={password} onChange={e => setPassword(e.target.value)} disabled={busy} hint={register ? l('建议使用密码管理器生成的长密码。', 'Use a long password generated by your password manager.') : undefined} />
        {register && <Input label={l('确认密码', 'Confirm password')} type="password" required allowTogglePassword autoComplete="new-password" value={confirmation} onChange={e => setConfirmation(e.target.value)} disabled={busy} />}
        {joining && <Input label={l('邀请码', 'Invitation code')} type="password" required allowTogglePassword autoComplete="off" value={token} onChange={e => setToken(e.target.value)} disabled={busy} />}
        {accountMode && register && !joining && <div className="space-y-3">
          <Input label={l('初始化凭证', 'Setup token')} type="password" required allowTogglePassword autoComplete="off" value={token} onChange={e => setToken(e.target.value)} disabled={busy} />
          <details className="text-sm leading-6 text-secondary-text">
            <summary className="cursor-pointer text-primary">{l('如何获取初始化凭证？', 'How do I get a setup token?')}</summary>
            <p className="mt-2">{l('在部署主机的项目目录中，使用运行服务的同一环境执行：', 'In the project directory on the deployment host, using the same environment as the server, run:')}</p>
            <code className="my-2 block overflow-x-auto rounded-lg bg-hover px-3 py-2 text-xs">python -m src.auth setup_token</code>
            <p>{l('凭证 30 分钟有效，仅首次设置需要。不要分享给他人。', 'The token expires in 30 minutes and is only needed for first setup. Do not share it.')}</p>
          </details>
        </div>}
        {mismatch && <p role="alert" className="text-sm text-danger">{l('两次输入的密码不一致。', 'Passwords do not match.')}</p>}
        {error != null && <p role="alert" className="text-sm text-danger">{accountErrorMessage(error, l)}</p>}
        <Button type="submit" className="h-12 w-full" isLoading={busy}>{migrate ? l('验证并保存账户', 'Verify & save account') : register ? l('创建账户并进入', 'Create account & continue') : l('登录', 'Sign in')}</Button>
      </form>
      {registrationMode === 'invite' && <button type="button" disabled={busy} className="mt-4 min-h-11 w-full text-sm text-primary" onClick={() => { setJoining(!joining); setToken(''); setError(undefined); setMismatch(false); }}>
        {joining ? l('已有账户？返回登录', 'Already registered? Sign in') : l('收到邀请？创建私有工作区', 'Have an invitation? Create your workspace')}
      </button>}
      <Link to="/try" className="btn-secondary mt-4 flex min-h-12 w-full items-center justify-center">{l('先体验一下 · 无需注册', 'Explore the demo · no signup')}</Link>
      {!register && !multiUserEnabled && <details className="mt-6 text-sm leading-6 text-secondary-text">
        <summary className="cursor-pointer">{l('忘记密码？', 'Forgot password?')}</summary>
        <p className="mt-2">{l('请在部署主机的项目目录中，使用同一服务环境执行以下命令。系统不提供未经验证的网页重置入口。', 'Run this command in the project directory on the deployment host using the server environment. There is no unauthenticated web reset endpoint.')}</p>
        <code className="mt-2 block overflow-x-auto rounded-lg bg-hover px-3 py-2 text-xs">python -m src.auth reset_password</code>
      </details>}
      <p className="mt-10 border-t border-border pt-5 text-xs leading-5 text-secondary-text">{multiUserEnabled ? l('邀请制注册。账户之间的持仓、报告与对话互不共享。需要邀请或恢复账户时，请联系部署管理员。', 'Invitation-only registration. Holdings, reports and chats are not shared between accounts. Contact the deployment administrator for invitations or account recovery.') : l('这是你部署的独立实例，不是公共多人注册服务。', 'This is your self-hosted instance, not a public multi-user service.')}</p>
    </section>
  </main>;
}
